{% set name = "pydflow" %}
{% set version = "1.8.109" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a8f761a3deec44b5c7aaeb246519ce478bef041d9b14b178adce5dc7c3d96d08

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - dflow = dflow.main:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - six
    - python-dateutil
    - urllib3
    - certifi
    - argo-workflows 5.0.0
    - jsonpickle
    - minio
    - python-kubernetes
    - pyyaml
    - cloudpickle 2.2.0
    - requests
    - tqdm
    - psutil
    - filelock

test:
  imports:
    - dflow
    - dflow.python
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - dflow -h
    - pip check

about:
  home: https://github.com/deepmodeling/dflow
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: Dflow is a Python framework for constructing scientific computing workflows employing Argo Workflows as the workflow engine.
  doc_url: https://github.com/deepmodeling/dflow
  dev_url: https://github.com/deepmodeling/dflow

extra:
  recipe-maintainers:
    - njzjz
    - zjgemi
