{% set name = "pydflow" %}
{% set version = "1.8.90" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 33f0fa27b36ee52730578507cbbf5d6663a98d5939aac12074de6350043b3384

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - dflow = dflow.main:main

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - python >=3.6
    - six
    - python-dateutil
    - urllib3
    - certifi
    - argo-workflows 5.0.0
    - jsonpickle
    - minio
    - python-kubernetes
    - pyyaml
    - cloudpickle 2.2.0
    - requests
    - tqdm
    - psutil

test:
  imports:
    - dflow
    - dflow.python
  requires:
    - pip
  commands:
    - dflow -h
    - pip check

about:
  home: https://github.com/deepmodeling/dflow
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: Dflow is a Python framework for constructing scientific computing workflows employing Argo Workflows as the workflow engine.
  doc_url: https://github.com/deepmodeling/dflow
  dev_url: https://github.com/deepmodeling/dflow

extra:
  recipe-maintainers:
    - njzjz
    - zjgemi
